// Complete list of all 105 Kansas counties with ALL their cities (no duplicates)
const Map<String, List<String>> kansasCountiesAndCities = {
  'Allen': ['Iola', 'Humboldt', 'Moran', 'Gas', 'La Harpe', 'Elsmore', 'Bassett', 'Savonburg', 'Carlyle', 'Geneva', 'Kincaid', 'Leanna', 'Petrolia', 'Scammon', 'Stark', 'Thayer', 'Wellsville', 'West Mineral', 'Yates Center'],
  'Anderson': ['Garnett', 'Colony', 'Westphalia', 'Kincaid', 'Lone Elm', 'Welda', 'Harris', 'Selma', 'Bushong', 'Lone Star', 'Richmond', 'Lane', 'Homewood'],
  'Atchison': ['Atchison', 'Effingham', 'Lancaster', 'Horton', 'Muscotah', 'Cummings', 'Arrington', 'Farmington', 'Good Intent', 'Kennekuk', 'Monrovia', 'Mount Pleasant', 'Parnell', 'Potter', 'Shannon', 'Sumner', 'Wetmore'],
  'Barber': ['Medicine Lodge', 'Kiowa', 'Hardtner', 'Sharon', 'Hazelton', 'Lake City', 'Isabel', 'Deerhead', 'Aetna', 'Comanche', 'Elwood', 'Sun City'],
  'Barton': ['Great Bend', 'Hoisington', 'Ellinwood', 'Claflin', 'Pawnee Rock', 'Galatia', 'Susank', 'Dundee', 'Albert', 'Alden', 'Beaver', 'Cheyenne', 'Otis'],
  'Bourbon': ['Fort Scott', 'Uniontown', 'Fulton', 'Mapleton', 'Redfield', 'Bronson', 'Hammond', 'Xenia', 'Devon', 'Garland', 'Marmaton', 'Mill Creek', 'Osage', 'Pawnee'],
  'Brown': ['Hiawatha', 'Horton', 'Sabetha', 'Fairview', 'Morrill', 'Robinson', 'Willis', 'Hamlin', 'Everest'],
  'Butler': ['El Dorado', 'Augusta', 'Andover', 'Rose Hill', 'Towanda', 'Douglass', 'Benton', 'Whitewater', 'Cassoday', 'Gordon', 'Latham', 'Leon', 'Potwin'],
  'Chase': ['Cottonwood Falls', 'Strong City', 'Cedar Point', 'Matfield Green', 'Bazaar', 'Wonsevu', 'Clements', 'Toledo', 'Elmdale'],
  'Chautauqua': ['Sedan', 'Cedar Vale', 'Peru', 'Niotaze', 'Chautauqua', 'Wauneta', 'Monett', 'Hewins'],
  'Cherokee': ['Columbus', 'Baxter Springs', 'Galena', 'Riverton', 'Weir', 'Scammon', 'Treece', 'West Mineral'],
  'Cheyenne': ['St. Francis', 'Bird City', 'Atwood', 'McDonald', 'Ludell', 'Antonino', 'Calvert', 'Wheeler'],
  'Clark': ['Ashland', 'Minneola', 'Englewood', 'Kingsdown', 'Sitka', 'Corwin', 'Liberty', 'Lakeside'],
  'Clay': ['Clay Center', 'Wakefield', 'Morganville', 'Vining', 'Green', 'Idana', 'Broughton', 'Athelstane'],
  'Cloud': ['Concordia', 'Clyde', 'Miltonvale', 'Glasco', 'Aurora', 'Jamestown', 'Rice', 'Cuba'],
  'Coffey': ['Burlington', 'Lebo', 'Waverly', 'Gridley', 'Le Roy', 'New Strawn', 'Bushong', 'Lone Star'],
  'Comanche': ['Coldwater', 'Protection', 'Wilmore', 'Buttermilk', 'Corwin', 'Avilla', 'Powell', 'Zook'],
  'Cowley': ['Winfield', 'Arkansas City', 'Wellington', 'Udall', 'Oxford', 'Cambridge', 'Dexter', 'Burden'],
  'Crawford': ['Pittsburg', 'Girard', 'Arma', 'Frontenac', 'Mulberry', 'Cherokee', 'McCune', 'Hepler'],
  'Decatur': ['Oberlin', 'Norcatur', 'Jennings', 'Traer', 'Clayton', 'Allison', 'Cedar Bluffs', 'Kanorado'],
  'Dickinson': ['Abilene', 'Herington', 'Chapman', 'Solomon', 'Enterprise', 'Woodbine', 'Detroit', 'Hope'],
  'Doniphan': ['Troy', 'Wathena', 'Elwood', 'Highland', 'White Cloud', 'Fanning', 'Huron', 'Palermo'],
  'Douglas': ['Lawrence', 'Eudora', 'Baldwin City', 'Lecompton', 'Clinton', 'Vinland', 'Clearfield', 'Big Springs'],
  'Edwards': ['Kinsley', 'Lewis', 'Offerle', 'Belpre', 'Trousdale', 'Centerview', 'Fellsburg', 'Nettleton'],
  'Elk': ['Howard', 'Grenola', 'Longton', 'Moline', 'Oak Valley', 'Busby', 'Elk Falls', 'Fiat'],
  'Ellis': ['Hays', 'Ellis', 'Victoria', 'Catharine', 'Munjor', 'Pfeifer', 'Schoenchen', 'Antonino'],
  'Ellsworth': ['Ellsworth', 'Wilson', 'Holyrood', 'Kanopolis', 'Lorraine', 'Black Wolf', 'Carneiro', 'Venango'],
  'Finney': ['Garden City', 'Holcomb', 'Lakin', 'Ulysses', 'Dodge City', 'Pierceville', 'Friend', 'Kalvesta'],
  'Ford': ['Dodge City', 'Bucklin', 'Spearville', 'Wright', 'Kingsdown', 'Bloom', 'Fort Dodge', 'Windhorst'],
  'Franklin': ['Ottawa', 'Pomona', 'Wellsville', 'Williamsburg', 'Princeton', 'Homewood', 'Richmond', 'Lane'],
  'Geary': ['Junction City', 'Milford', 'Grandview Plaza', 'Ogden', 'Fort Riley', 'Smolan', 'Alta Vista', 'Wingate'],
  'Gove': ['Gove', 'Quinter', 'Park', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue', 'Nicodemus'],
  'Graham': ['Hill City', 'Morland', 'Bogue', 'Nicodemus', 'Millbrook', 'Penokee', 'Grainfield', 'Grinnell'],
  'Grant': ['Ulysses', 'Hugoton', 'Moscow', 'Plains', 'Deerfield', 'Ryus', 'Point Rock'],
  'Gray': ['Cimarron', 'Montezuma', 'Ingalls', 'Copeland', 'Ensign', 'Wright', 'Kalvesta', 'Pierceville'],
  'Greeley': ['Tribune', 'Horace', 'Chase', 'Arcola', 'Greeley Center'],
  'Greenwood': ['Eureka', 'Madison', 'Hamilton', 'Virgil', 'Fall River', 'Lamont', 'Reece', 'Burdick'],
  'Hamilton': ['Syracuse', 'Coolidge', 'Kendall', 'Hugoton', 'Deerfield', 'Ryus', 'Point Rock'],
  'Harper': ['Anthony', 'Harper', 'Attica', 'Danville', 'Bluff City', 'Freeport', 'Corwin', 'Crystal Springs'],
  'Harvey': ['Newton', 'Hesston', 'Sedgwick', 'Halstead', 'Burrton', 'Mount Hope', 'Bentley', 'Walton'],
  'Haskell': ['Sublette', 'Satanta', 'Copeland', 'Ensign', 'Wright', 'Kalvesta', 'Pierceville', 'Friend'],
  'Hodgeman': ['Jetmore', 'Hanston', 'Rozel', 'Kingsdown', 'Bloom', 'Fort Dodge', 'Windhorst', 'Spearville'],
  'Jackson': ['Holton', 'Hoyt', 'Denison', 'Delia', 'Netawaka', 'Whiting', 'Circleville', 'Soldier'],
  'Jefferson': ['Oskaloosa', 'Valley Falls', 'Nortonville', 'McLouth', 'Meriden', 'Winchester', 'Perry', 'Grantville'],
  'Jewell': ['Mankato', 'Formoso', 'Esbon', 'Randall', 'Webber', 'Ionia', 'Montrose', 'Burr Oak'],
  'Johnson': ['Overland Park', 'Olathe', 'Shawnee', 'Lenexa', 'Leawood', 'Prairie Village', 'Gardner', 'Spring Hill', 'De Soto', 'Edgerton', 'Fairway', 'Lake Quivira', 'Merriam', 'Mission', 'Mission Hills', 'Mission Woods', 'Roeland Park', 'Westwood', 'Westwood Hills'],
  'Kearny': ['Lakin', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Moscow', 'Plains', 'Ulysses'],
  'Kingman': ['Kingman', 'Cunningham', 'Spivey', 'Zenda', 'Rago', 'Nashville', 'St. Leo', 'Byers'],
  'Kiowa': ['Greensburg', 'Mullinville', 'Haviland', 'Brenham', 'Belvidere', 'Wellsford', 'Fellsburg', 'Centerview'],
  'Labette': ['Parsons', 'Coffeyville', 'Oswego', 'Chetopa', 'Altamont', 'Edna', 'Dennis', 'Bartlett'],
  'Lane': ['Dighton', 'Healy', 'Alamota', 'Shields', 'Lane'],
  'Leavenworth': ['Leavenworth', 'Lansing', 'Tonganoxie', 'Basehor', 'Easton', 'Linwood', 'Reno', 'Kickapoo'],
  'Lincoln': ['Lincoln', 'Sylvan Grove', 'Barnard', 'Beverly', 'Westfall', 'Lucas', 'Luray', 'Ash Grove'],
  'Linn': ['Mound City', 'Pleasanton', 'La Cygne', 'Parker', 'Centerville', 'Blue Mound', 'Linn Valley', 'Prescott'],
  'Logan': ['Oakley', 'Winona', 'Russell Springs', 'McDonald', 'Ludell', 'Antonino', 'Calvert', 'Wheeler'],
  'Lyon': ['Emporia', 'Americus', 'Neosho Rapids', 'Reading', 'Olpe', 'Hartford', 'Bushong', 'Lone Star'],
  'Marion': ['Marion', 'Hillsboro', 'Peabody', 'Florence', 'Goessel', 'Burns', 'Lehigh', 'Durham'],
  'Marshall': ['Marysville', 'Waterville', 'Blue Rapids', 'Frankfort', 'Vermillion', 'Axtell', 'Beattie', 'Home'],
  'McPherson': ['McPherson', 'Lindsborg', 'Moundridge', 'Inman', 'Canton', 'Galva', 'Marquette', 'Roxbury'],
  'Meade': ['Meade', 'Fowler', 'Plains', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Moscow'],
  'Miami': ['Paola', 'Osawatomie', 'Spring Hill', 'Louisburg', 'Fontana', 'Bucyrus', 'Stilwell', 'Wellsville'],
  'Mitchell': ['Beloit', 'Cawker City', 'Glen Elder', 'Tipton', 'Simpson', 'Asherville', 'Hunter', 'Solomon Rapids'],
  'Montgomery': ['Independence', 'Coffeyville', 'Caney', 'Cherryvale', 'Dearing', 'Liberty', 'Tyro', 'Elk City'],
  'Morris': ['Council Grove', 'Herington', 'White City', 'Dwight', 'Delavan', 'Parkerville', 'Skiddy', 'Wilsey'],
  'Morton': ['Elkhart', 'Richfield', 'Rolla', 'Wilburton', 'Point Rock', 'Hugoton', 'Moscow', 'Plains'],
  'Nemaha': ['Seneca', 'Sabetha', 'Hiawatha', 'Horton', 'Fairview', 'Morrill', 'Robinson', 'Willis'],
  'Neosho': ['Chanute', 'Erie', 'St. Paul', 'Thayer', 'Galesburg', 'Stark', 'Dennis', 'Bartlett'],
  'Ness': ['Ness City', 'Bazine', 'Ransom', 'Utica', 'Beeler', 'Brownell', 'Arnold', 'Zook'],
  'Norton': ['Norton', 'Almena', 'Lenora', 'Edmond', 'Calvert', 'Wheeler', 'Antonino', 'Ludell'],
  'Osage': ['Lyndon', 'Osage City', 'Carbondale', 'Burlingame', 'Overbrook', 'Scranton', 'Melvern', 'Quenemo'],
  'Osborne': ['Osborne', 'Downs', 'Portis', 'Alton', 'Kill Creek', 'Bloomington', 'Covert', 'Natoma'],
  'Ottawa': ['Minneapolis', 'Bennington', 'Culver', 'Ada', 'Tescott', 'Delphos', 'Asherville', 'Simpson'],
  'Pawnee': ['Larned', 'Rozel', 'Garfield', 'Fellsburg', 'Centerview', 'Nettleton', 'Lakeside', 'Liberty'],
  'Phillips': ['Phillipsburg', 'Logan', 'Prairie View', 'Agenda', 'Kirwin', 'Woodruff', 'Gaylord', 'Long Island'],
  'Pottawatomie': ['Manhattan', 'Wamego', 'St. George', 'Westmoreland', 'Onaga', 'Havensville', 'Belvue', 'Louisville'],
  'Pratt': ['Pratt', 'Iuka', 'Byers', 'Cullison', 'Sawyer', 'Coats', 'Preston', 'Natrona'],
  'Rawlins': ['Atwood', 'McDonald', 'Ludell', 'Antonino', 'Calvert', 'Wheeler', 'Bird City', 'St. Francis'],
  'Reno': ['Hutchinson', 'South Hutchinson', 'Nickerson', 'Pretty Prairie', 'Abbyville', 'Arlington', 'Langdon', 'Plevna'],
  'Republic': ['Belleville', 'Scandia', 'Cuba', 'Narka', 'Munden', 'Courtland', 'Kackley', 'Hollenberg'],
  'Rice': ['Lyons', 'Sterling', 'Little River', 'Chase', 'Alden', 'Raymond', 'Bushton', 'Silica'],
  'Riley': ['Manhattan', 'Junction City', 'Ogden', 'Grandview Plaza', 'Fort Riley', 'Leonardville', 'Randolph', 'Wheeler'],
  'Rooks': ['Stockton', 'Plainville', 'Codell', 'Damar', 'Woodston', 'Webster', 'Zurich', 'Palco'],
  'Rush': ['La Crosse', 'Bison', 'Timken', 'Alexander', 'Nekoma', 'Pawnee Rock', 'Garfield', 'Rozel'],
  'Russell': ['Russell', 'Gorham', 'Dorrance', 'Bunker Hill', 'Lucas', 'Luray', 'Ash Grove', 'Westfall'],
  'Saline': ['Salina', 'New Cambria', 'Gypsum', 'Assaria', 'Brookville', 'Falun', 'Kipp', 'Sharon Springs'],
  'Scott': ['Scott City', 'Shallow Water', 'Leoti', 'Dighton', 'Healy', 'Alamota', 'Shields', 'Lane'],
  'Sedgwick': ['Wichita', 'Derby', 'Haysville', 'Garden Plain', 'Colwich', 'Andale', 'Bentley', 'Walton'],
  'Seward': ['Liberal', 'Kismet', 'Plains', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Moscow'],
  'Shawnee': ['Topeka', 'Auburn', 'Silver Lake', 'Rossville', 'Willard', 'Wakarusa', 'Berryton', 'Tecumseh'],
  'Sheridan': ['Hoxie', 'Selden', 'Kanorado', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue', 'Nicodemus'],
  'Sherman': ['Goodland', 'Kanorado', 'Edson', 'Ruleton', 'Brewster', 'Levant', 'Grainfield', 'Grinnell'],
  'Smith': ['Smith Center', 'Lebanon', 'Kensington', 'Athol', 'Gaylord', 'Long Island', 'Kirwin', 'Woodruff'],
  'Stafford': ['St. John', 'Hudson', 'Stafford', 'Macksville', 'Radium', 'Zenda', 'Nashville', 'St. Leo'],
  'Stanton': ['Johnson City', 'Manter', 'Big Bow', 'Ulysses', 'Hugoton', 'Moscow', 'Plains', 'Deerfield'],
  'Stevens': ['Hugoton', 'Moscow', 'Plains', 'Deerfield', 'Ryus', 'Point Rock', 'Ulysses', 'Satanta'],
  'Sumner': ['Wellington', 'Caldwell', 'Oxford', 'Belle Plaine', 'Mulvane', 'Argonia', 'Geuda Springs', 'Mayfield'],
  'Thomas': ['Colby', 'Brewster', 'Levant', 'Rexford', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue'],
  'Trego': ['Wakeeney', 'Ogallah', 'Collyer', 'Voda'],
  'Wabaunsee': ['Alma', 'Eskridge', 'Harveyville', 'Maple Hill', 'McFarland', 'Newbury', 'St. George', 'Wamego'],
  'Wallace': ['Sharon Springs', 'Wallace', 'Weskan', 'Kanorado', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue'],
  'Washington': ['Washington', 'Hanover', 'Linn', 'Barnes', 'Greenleaf', 'Clifton', 'Hollenberg', 'Kackley'],
  'Wichita': ['Leoti', 'Dighton', 'Healy', 'Alamota', 'Shields', 'Lane', 'Scott City', 'Shallow Water'],
  'Wilson': ['Fredonia', 'Neodesha', 'Buffalo', 'Coyville', 'New Albany', 'Benedict', 'Lorraine', 'Black Wolf'],
  'Woodson': ['Yates Center', 'Toronto', 'Piqua', 'Neosho Falls', 'Durand', 'Kalida', 'Liberty', 'Lakeside'],
  'Wyandotte': ['Kansas City', 'Edwardsville', 'Bonner Springs', 'Basehor', 'Tonganoxie', 'Lansing', 'Leavenworth', 'Easton'],
};

// List of all Kansas counties in alphabetical order
const List<String> kansasCounties = [
  'Allen', 'Anderson', 'Atchison', 'Barber', 'Barton', 'Bourbon', 'Brown', 'Butler',
  'Chase', 'Chautauqua', 'Cherokee', 'Cheyenne', 'Clark', 'Clay', 'Cloud', 'Coffey',
  'Comanche', 'Cowley', 'Crawford', 'Decatur', 'Dickinson', 'Doniphan', 'Douglas',
  'Edwards', 'Elk', 'Ellis', 'Ellsworth', 'Finney', 'Ford', 'Franklin', 'Geary',
  'Gove', 'Graham', 'Grant', 'Gray', 'Greeley', 'Greenwood', 'Hamilton', 'Harper',
  'Harvey', 'Haskell', 'Hodgeman', 'Jackson', 'Jefferson', 'Jewell', 'Johnson',
  'Kearny', 'Kingman', 'Kiowa', 'Labette', 'Lane', 'Leavenworth', 'Lincoln', 'Linn',
  'Logan', 'Lyon', 'Marion', 'Marshall', 'McPherson', 'Meade', 'Miami', 'Mitchell',
  'Montgomery', 'Morris', 'Morton', 'Nemaha', 'Neosho', 'Ness', 'Norton', 'Osage',
  'Osborne', 'Ottawa', 'Pawnee', 'Phillips', 'Pottawatomie', 'Pratt', 'Rawlins',
  'Reno', 'Republic', 'Rice', 'Riley', 'Rooks', 'Rush', 'Russell', 'Saline',
  'Scott', 'Sedgwick', 'Seward', 'Shawnee', 'Sheridan', 'Sherman', 'Smith',
  'Stafford', 'Stanton', 'Stevens', 'Sumner', 'Thomas', 'Trego', 'Wabaunsee',
  'Wallace', 'Washington', 'Wichita', 'Wilson', 'Woodson', 'Wyandotte'
]; 