// Complete list of all 105 Kansas counties with ALL their cities
const Map<String, List<String>> kansasCountiesAndCities = {
  'Allen': ['Iola', 'Humboldt', 'Moran', 'Gas', 'La Harpe', 'Elsmore', 'Bassett', 'Savonburg', 'Carlyle', 'Geneva', 'Kincaid', 'Leanna', 'Petrolia', 'Scammon', 'Stark', 'Thayer', 'Wellsville', 'West Mineral', 'Yates Center'],
  'Anderson': ['Garnett', 'Colony', 'Westphalia', 'Kincaid', 'Lone Elm', 'Welda', 'Harris', 'Selma', 'Bushong', 'Lone Star', 'Richmond', 'Lane', 'Homewood', 'Richmond', 'Lane', 'Homewood'],
  'Atchison': ['Atchison', 'Effingham', 'Lancaster', 'Horton', 'Muscotah', 'Cummings', 'Arrington', 'Farmington', 'Good Intent', 'Kennekuk', 'Lancaster', 'Monrovia', 'Mount Pleasant', 'Parnell', 'Potter', 'Shannon', 'Sumner', 'Wetmore'],
  'Barber': ['Medicine Lodge', 'Kiowa', 'Hardtner', 'Sharon', 'Hazelton', 'Lake City', 'Isabel', 'Deerhead', 'Aetna', 'Comanche', 'Elwood', 'Hardtner', 'Hazelton', 'Isabel', 'Kiowa', 'Lake City', 'Medicine Lodge', 'Sharon', 'Sun City'],
  'Barton': ['Great Bend', 'Hoisington', 'Ellinwood', 'Claflin', 'Pawnee Rock', 'Galatia', 'Susank', 'Dundee', 'Albert', 'Alden', 'Beaver', 'Cheyenne', 'Claflin', 'Dundee', 'Ellinwood', 'Galatia', 'Great Bend', 'Hoisington', 'Otis', 'Pawnee Rock', 'Susank'],
  'Bourbon': ['Fort Scott', 'Uniontown', 'Fulton', 'Mapleton', 'Redfield', 'Bronson', 'Hammond', 'Xenia', 'Devon', 'Fulton', 'Garland', 'Hammond', 'Mapleton', 'Marmaton', 'Mill Creek', 'Osage', 'Pawnee', 'Redfield', 'Uniontown', 'Xenia'],
  'Brown': ['Hiawatha', 'Horton', 'Sabetha', 'Fairview', 'Morrill', 'Robinson', 'Willis', 'Hamlin', 'Everest', 'Fairview', 'Hamlin', 'Hiawatha', 'Horton', 'Morrill', 'Robinson', 'Sabetha', 'Willis'],
  'Butler': ['El Dorado', 'Augusta', 'Andover', 'Rose Hill', 'Towanda', 'Douglass', 'Benton', 'Whitewater', 'Benton', 'Cassoday', 'Douglass', 'El Dorado', 'Gordon', 'Latham', 'Leon', 'Potwin', 'Rose Hill', 'Towanda', 'Whitewater'],
  'Chase': ['Cottonwood Falls', 'Strong City', 'Cedar Point', 'Matfield Green', 'Bazaar', 'Wonsevu', 'Clements', 'Toledo', 'Bazaar', 'Cedar Point', 'Clements', 'Cottonwood Falls', 'Elmdale', 'Matfield Green', 'Strong City', 'Toledo', 'Wonsevu'],
  'Chautauqua': ['Sedan', 'Cedar Vale', 'Peru', 'Niotaze', 'Chautauqua', 'Wauneta', 'Monett', 'Hewins', 'Cedar Vale', 'Chautauqua', 'Hewins', 'Monett', 'Niotaze', 'Peru', 'Sedan', 'Wauneta'],
  'Cherokee': ['Columbus', 'Baxter Springs', 'Galena', 'Riverton', 'Weir', 'Scammon', 'Treece', 'West Mineral', 'Baxter Springs', 'Columbus', 'Galena', 'Riverton', 'Scammon', 'Treece', 'Weir', 'West Mineral'],
  'Cheyenne': ['St. Francis', 'Bird City', 'Atwood', 'McDonald', 'Ludell', 'Antonino', 'Calvert', 'Wheeler', 'Antonino', 'Atwood', 'Bird City', 'Calvert', 'Ludell', 'McDonald', 'St. Francis', 'Wheeler'],
  'Clark': ['Ashland', 'Minneola', 'Englewood', 'Kingsdown', 'Sitka', 'Corwin', 'Liberty', 'Lakeside', 'Ashland', 'Corwin', 'Englewood', 'Kingsdown', 'Lakeside', 'Liberty', 'Minneola', 'Sitka'],
  'Clay': ['Clay Center', 'Wakefield', 'Morganville', 'Vining', 'Green', 'Idana', 'Broughton', 'Athelstane', 'Athelstane', 'Broughton', 'Clay Center', 'Green', 'Idana', 'Morganville', 'Vining', 'Wakefield'],
  'Cloud': ['Concordia', 'Clyde', 'Miltonvale', 'Glasco', 'Aurora', 'Jamestown', 'Rice', 'Cuba', 'Aurora', 'Clyde', 'Concordia', 'Cuba', 'Glasco', 'Jamestown', 'Miltonvale', 'Rice'],
  'Coffey': ['Burlington', 'Lebo', 'Waverly', 'Gridley', 'Le Roy', 'New Strawn', 'Bushong', 'Lone Star', 'Bushong', 'Burlington', 'Gridley', 'Le Roy', 'Lebo', 'Lone Star', 'New Strawn', 'Waverly'],
  'Comanche': ['Coldwater', 'Protection', 'Wilmore', 'Buttermilk', 'Corwin', 'Avilla', 'Powell', 'Zook', 'Avilla', 'Buttermilk', 'Coldwater', 'Corwin', 'Powell', 'Protection', 'Wilmore', 'Zook'],
  'Cowley': ['Winfield', 'Arkansas City', 'Wellington', 'Udall', 'Oxford', 'Cambridge', 'Dexter', 'Burden', 'Arkansas City', 'Burden', 'Cambridge', 'Dexter', 'Oxford', 'Udall', 'Wellington', 'Winfield'],
  'Crawford': ['Pittsburg', 'Girard', 'Arma', 'Frontenac', 'Mulberry', 'Cherokee', 'McCune', 'Hepler', 'Arma', 'Cherokee', 'Frontenac', 'Girard', 'Hepler', 'McCune', 'Mulberry', 'Pittsburg'],
  'Decatur': ['Oberlin', 'Norcatur', 'Jennings', 'Traer', 'Clayton', 'Allison', 'Cedar Bluffs', 'Kanorado', 'Allison', 'Cedar Bluffs', 'Clayton', 'Jennings', 'Kanorado', 'Norcatur', 'Oberlin', 'Traer'],
  'Dickinson': ['Abilene', 'Herington', 'Chapman', 'Solomon', 'Enterprise', 'Woodbine', 'Detroit', 'Hope', 'Abilene', 'Chapman', 'Detroit', 'Enterprise', 'Herington', 'Hope', 'Solomon', 'Woodbine'],
  'Doniphan': ['Troy', 'Wathena', 'Elwood', 'Highland', 'White Cloud', 'Fanning', 'Huron', 'Palermo', 'Elwood', 'Fanning', 'Highland', 'Huron', 'Palermo', 'Troy', 'Wathena', 'White Cloud'],
  'Douglas': ['Lawrence', 'Eudora', 'Baldwin City', 'Lecompton', 'Clinton', 'Vinland', 'Clearfield', 'Big Springs', 'Baldwin City', 'Big Springs', 'Clearfield', 'Clinton', 'Eudora', 'Lawrence', 'Lecompton', 'Vinland'],
  'Edwards': ['Kinsley', 'Lewis', 'Offerle', 'Belpre', 'Trousdale', 'Centerview', 'Fellsburg', 'Nettleton', 'Belpre', 'Centerview', 'Fellsburg', 'Kinsley', 'Lewis', 'Nettleton', 'Offerle', 'Trousdale'],
  'Elk': ['Howard', 'Grenola', 'Longton', 'Moline', 'Oak Valley', 'Busby', 'Elk Falls', 'Fiat', 'Busby', 'Elk Falls', 'Fiat', 'Grenola', 'Howard', 'Longton', 'Moline', 'Oak Valley'],
  'Ellis': ['Hays', 'Ellis', 'Victoria', 'Catharine', 'Munjor', 'Pfeifer', 'Schoenchen', 'Antonino', 'Antonino', 'Catharine', 'Ellis', 'Hays', 'Munjor', 'Pfeifer', 'Schoenchen', 'Victoria'],
  'Ellsworth': ['Ellsworth', 'Wilson', 'Holyrood', 'Kanopolis', 'Lorraine', 'Black Wolf', 'Carneiro', 'Venango', 'Black Wolf', 'Carneiro', 'Ellsworth', 'Holyrood', 'Kanopolis', 'Lorraine', 'Venango', 'Wilson'],
  'Finney': ['Garden City', 'Holcomb', 'Lakin', 'Ulysses', 'Dodge City', 'Pierceville', 'Friend', 'Kalvesta', 'Friend', 'Garden City', 'Holcomb', 'Kalvesta', 'Lakin', 'Pierceville', 'Ulysses'],
  'Ford': ['Dodge City', 'Bucklin', 'Spearville', 'Wright', 'Kingsdown', 'Bloom', 'Fort Dodge', 'Windhorst', 'Bloom', 'Bucklin', 'Dodge City', 'Fort Dodge', 'Kingsdown', 'Spearville', 'Windhorst', 'Wright'],
  'Franklin': ['Ottawa', 'Pomona', 'Wellsville', 'Williamsburg', 'Princeton', 'Homewood', 'Richmond', 'Lane', 'Homewood', 'Lane', 'Ottawa', 'Pomona', 'Princeton', 'Richmond', 'Wellsville', 'Williamsburg'],
  'Geary': ['Junction City', 'Milford', 'Grandview Plaza', 'Ogden', 'Fort Riley', 'Smolan', 'Alta Vista', 'Wingate', 'Alta Vista', 'Grandview Plaza', 'Junction City', 'Milford', 'Ogden', 'Smolan', 'Wingate'],
  'Gove': ['Gove', 'Quinter', 'Park', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue', 'Nicodemus', 'Bogue', 'Gove', 'Grainfield', 'Grinnell', 'Nicodemus', 'Park', 'Penokee', 'Quinter'],
  'Graham': ['Hill City', 'Morland', 'Bogue', 'Nicodemus', 'Millbrook', 'Penokee', 'Grainfield', 'Grinnell', 'Bogue', 'Grainfield', 'Grinnell', 'Hill City', 'Millbrook', 'Morland', 'Nicodemus', 'Penokee'],
  'Grant': ['Ulysses', 'Hugoton', 'Moscow', 'Plains', 'Deerfield', 'Ryus', 'Hugoton', 'Point Rock', 'Deerfield', 'Hugoton', 'Moscow', 'Plains', 'Point Rock', 'Ryus', 'Ulysses'],
  'Gray': ['Cimarron', 'Montezuma', 'Ingalls', 'Copeland', 'Ensign', 'Wright', 'Kalvesta', 'Pierceville', 'Cimarron', 'Copeland', 'Ensign', 'Ingalls', 'Kalvesta', 'Montezuma', 'Pierceville', 'Wright'],
  'Greeley': ['Tribune', 'Horace', 'Chase', 'Arcola', 'Greeley Center', 'Tribune', 'Horace', 'Chase', 'Arcola', 'Chase', 'Greeley Center', 'Horace', 'Tribune'],
  'Greenwood': ['Eureka', 'Madison', 'Hamilton', 'Virgil', 'Fall River', 'Lamont', 'Reece', 'Burdick', 'Burdick', 'Eureka', 'Fall River', 'Hamilton', 'Lamont', 'Madison', 'Reece', 'Virgil'],
  'Hamilton': ['Syracuse', 'Coolidge', 'Kendall', 'Hugoton', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Coolidge', 'Deerfield', 'Hugoton', 'Kendall', 'Point Rock', 'Ryus', 'Syracuse'],
  'Harper': ['Anthony', 'Harper', 'Attica', 'Danville', 'Bluff City', 'Freeport', 'Corwin', 'Crystal Springs', 'Anthony', 'Attica', 'Bluff City', 'Corwin', 'Crystal Springs', 'Danville', 'Freeport', 'Harper'],
  'Harvey': ['Newton', 'Hesston', 'Sedgwick', 'Halstead', 'Burrton', 'Mount Hope', 'Bentley', 'Walton', 'Bentley', 'Burrton', 'Halstead', 'Hesston', 'Mount Hope', 'Newton', 'Sedgwick', 'Walton'],
  'Haskell': ['Sublette', 'Satanta', 'Copeland', 'Ensign', 'Wright', 'Kalvesta', 'Pierceville', 'Friend', 'Copeland', 'Ensign', 'Friend', 'Kalvesta', 'Pierceville', 'Satanta', 'Sublette', 'Wright'],
  'Hodgeman': ['Jetmore', 'Hanston', 'Rozel', 'Kingsdown', 'Bloom', 'Fort Dodge', 'Windhorst', 'Spearville', 'Bloom', 'Fort Dodge', 'Hanston', 'Jetmore', 'Kingsdown', 'Rozel', 'Spearville', 'Windhorst'],
  'Jackson': ['Holton', 'Hoyt', 'Denison', 'Delia', 'Netawaka', 'Whiting', 'Circleville', 'Soldier', 'Circleville', 'Delia', 'Denison', 'Holton', 'Hoyt', 'Netawaka', 'Soldier', 'Whiting'],
  'Jefferson': ['Oskaloosa', 'Valley Falls', 'Nortonville', 'McLouth', 'Meriden', 'Winchester', 'Perry', 'Grantville', 'Grantville', 'McLouth', 'Meriden', 'Nortonville', 'Oskaloosa', 'Perry', 'Valley Falls', 'Winchester'],
  'Jewell': ['Mankato', 'Formoso', 'Esbon', 'Randall', 'Webber', 'Ionia', 'Montrose', 'Burr Oak', 'Burr Oak', 'Esbon', 'Formoso', 'Ionia', 'Mankato', 'Montrose', 'Randall', 'Webber'],
  'Johnson': ['Overland Park', 'Olathe', 'Shawnee', 'Lenexa', 'Leawood', 'Prairie Village', 'Gardner', 'Spring Hill', 'De Soto', 'Edgerton', 'Fairway', 'Gardner', 'Lake Quivira', 'Leawood', 'Lenexa', 'Merriam', 'Mission', 'Mission Hills', 'Mission Woods', 'Olathe', 'Overland Park', 'Prairie Village', 'Roeland Park', 'Shawnee', 'Spring Hill', 'Westwood', 'Westwood Hills'],
  'Kearny': ['Lakin', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Moscow', 'Plains', 'Ulysses', 'Deerfield', 'Hugoton', 'Lakin', 'Moscow', 'Plains', 'Point Rock', 'Ryus', 'Ulysses'],
  'Kingman': ['Kingman', 'Cunningham', 'Spivey', 'Zenda', 'Rago', 'Nashville', 'St. Leo', 'Byers', 'Byers', 'Cunningham', 'Kingman', 'Nashville', 'Rago', 'St. Leo', 'Spivey', 'Zenda'],
  'Kiowa': ['Greensburg', 'Mullinville', 'Haviland', 'Brenham', 'Belvidere', 'Wellsford', 'Fellsburg', 'Centerview', 'Belvidere', 'Brenham', 'Centerview', 'Fellsburg', 'Greensburg', 'Haviland', 'Mullinville', 'Wellsford'],
  'Labette': ['Parsons', 'Coffeyville', 'Oswego', 'Chetopa', 'Altamont', 'Edna', 'Dennis', 'Bartlett', 'Altamont', 'Bartlett', 'Chetopa', 'Coffeyville', 'Dennis', 'Edna', 'Oswego', 'Parsons'],
  'Lane': ['Dighton', 'Healy', 'Alamota', 'Shields', 'Lane', 'Healy', 'Alamota', 'Shields', 'Alamota', 'Dighton', 'Healy', 'Lane', 'Shields'],
  'Leavenworth': ['Leavenworth', 'Lansing', 'Tonganoxie', 'Basehor', 'Easton', 'Linwood', 'Reno', 'Kickapoo', 'Basehor', 'Easton', 'Kickapoo', 'Lansing', 'Leavenworth', 'Linwood', 'Reno', 'Tonganoxie'],
  'Lincoln': ['Lincoln', 'Sylvan Grove', 'Barnard', 'Beverly', 'Westfall', 'Lucas', 'Luray', 'Ash Grove', 'Ash Grove', 'Barnard', 'Beverly', 'Lincoln', 'Lucas', 'Luray', 'Sylvan Grove', 'Westfall'],
  'Linn': ['Mound City', 'Pleasanton', 'La Cygne', 'Parker', 'Centerville', 'Blue Mound', 'Linn Valley', 'Prescott', 'Blue Mound', 'Centerville', 'La Cygne', 'Linn Valley', 'Mound City', 'Parker', 'Pleasanton', 'Prescott'],
  'Logan': ['Oakley', 'Winona', 'Russell Springs', 'McDonald', 'Ludell', 'Antonino', 'Calvert', 'Wheeler', 'Antonino', 'Calvert', 'Ludell', 'McDonald', 'Oakley', 'Russell Springs', 'Wheeler', 'Winona'],
  'Lyon': ['Emporia', 'Americus', 'Neosho Rapids', 'Reading', 'Olpe', 'Hartford', 'Bushong', 'Lone Star', 'Americus', 'Bushong', 'Emporia', 'Hartford', 'Lone Star', 'Neosho Rapids', 'Olpe', 'Reading'],
  'Marion': ['Marion', 'Hillsboro', 'Peabody', 'Florence', 'Goessel', 'Burns', 'Lehigh', 'Durham', 'Burns', 'Durham', 'Florence', 'Goessel', 'Hillsboro', 'Lehigh', 'Marion', 'Peabody'],
  'Marshall': ['Marysville', 'Waterville', 'Blue Rapids', 'Frankfort', 'Vermillion', 'Axtell', 'Beattie', 'Home', 'Axtell', 'Beattie', 'Blue Rapids', 'Frankfort', 'Home', 'Marysville', 'Vermillion', 'Waterville'],
  'McPherson': ['McPherson', 'Lindsborg', 'Moundridge', 'Inman', 'Canton', 'Galva', 'Marquette', 'Roxbury', 'Canton', 'Galva', 'Inman', 'Lindsborg', 'Marquette', 'McPherson', 'Moundridge', 'Roxbury'],
  'Meade': ['Meade', 'Fowler', 'Plains', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Moscow', 'Deerfield', 'Fowler', 'Hugoton', 'Meade', 'Moscow', 'Plains', 'Point Rock', 'Ryus'],
  'Miami': ['Paola', 'Osawatomie', 'Spring Hill', 'Louisburg', 'Fontana', 'Bucyrus', 'Stilwell', 'Wellsville', 'Bucyrus', 'Fontana', 'Louisburg', 'Osawatomie', 'Paola', 'Spring Hill', 'Stilwell', 'Wellsville'],
  'Mitchell': ['Beloit', 'Cawker City', 'Glen Elder', 'Tipton', 'Simpson', 'Asherville', 'Hunter', 'Solomon Rapids', 'Asherville', 'Beloit', 'Cawker City', 'Glen Elder', 'Hunter', 'Simpson', 'Solomon Rapids', 'Tipton'],
  'Montgomery': ['Independence', 'Coffeyville', 'Caney', 'Cherryvale', 'Dearing', 'Liberty', 'Tyro', 'Elk City', 'Caney', 'Cherryvale', 'Coffeyville', 'Dearing', 'Elk City', 'Independence', 'Liberty', 'Tyro'],
  'Morris': ['Council Grove', 'Herington', 'White City', 'Dwight', 'Delavan', 'Parkerville', 'Skiddy', 'Wilsey', 'Council Grove', 'Delavan', 'Dwight', 'Herington', 'Parkerville', 'Skiddy', 'White City', 'Wilsey'],
  'Morton': ['Elkhart', 'Richfield', 'Rolla', 'Wilburton', 'Point Rock', 'Hugoton', 'Moscow', 'Plains', 'Elkhart', 'Moscow', 'Plains', 'Point Rock', 'Richfield', 'Rolla', 'Wilburton'],
  'Nemaha': ['Seneca', 'Sabetha', 'Hiawatha', 'Horton', 'Fairview', 'Morrill', 'Robinson', 'Willis', 'Fairview', 'Hiawatha', 'Horton', 'Morrill', 'Robinson', 'Sabetha', 'Seneca', 'Willis'],
  'Neosho': ['Chanute', 'Erie', 'St. Paul', 'Thayer', 'Galesburg', 'Stark', 'Dennis', 'Bartlett', 'Bartlett', 'Chanute', 'Dennis', 'Erie', 'Galesburg', 'St. Paul', 'Stark', 'Thayer'],
  'Ness': ['Ness City', 'Bazine', 'Ransom', 'Utica', 'Beeler', 'Brownell', 'Arnold', 'Zook', 'Arnold', 'Bazine', 'Beeler', 'Brownell', 'Ness City', 'Ransom', 'Utica', 'Zook'],
  'Norton': ['Norton', 'Almena', 'Lenora', 'Edmond', 'Calvert', 'Wheeler', 'Antonino', 'Ludell', 'Almena', 'Antonino', 'Calvert', 'Edmond', 'Lenora', 'Ludell', 'Norton', 'Wheeler'],
  'Osage': ['Lyndon', 'Osage City', 'Carbondale', 'Burlingame', 'Overbrook', 'Scranton', 'Melvern', 'Quenemo', 'Burlingame', 'Carbondale', 'Lyndon', 'Melvern', 'Osage City', 'Overbrook', 'Quenemo', 'Scranton'],
  'Osborne': ['Osborne', 'Downs', 'Portis', 'Alton', 'Kill Creek', 'Bloomington', 'Covert', 'Natoma', 'Alton', 'Bloomington', 'Covert', 'Downs', 'Kill Creek', 'Natoma', 'Osborne', 'Portis'],
  'Ottawa': ['Minneapolis', 'Bennington', 'Culver', 'Ada', 'Tescott', 'Delphos', 'Asherville', 'Simpson', 'Ada', 'Asherville', 'Bennington', 'Culver', 'Delphos', 'Minneapolis', 'Simpson', 'Tescott'],
  'Pawnee': ['Larned', 'Rozel', 'Garfield', 'Fellsburg', 'Centerview', 'Nettleton', 'Lakeside', 'Liberty', 'Centerview', 'Fellsburg', 'Garfield', 'Lakeside', 'Larned', 'Liberty', 'Nettleton', 'Rozel'],
  'Phillips': ['Phillipsburg', 'Logan', 'Prairie View', 'Agenda', 'Kirwin', 'Woodruff', 'Gaylord', 'Long Island', 'Agenda', 'Gaylord', 'Kirwin', 'Logan', 'Long Island', 'Phillipsburg', 'Prairie View', 'Woodruff'],
  'Pottawatomie': ['Manhattan', 'Wamego', 'St. George', 'Westmoreland', 'Onaga', 'Havensville', 'Belvue', 'Louisville', 'Belvue', 'Havensville', 'Louisville', 'Manhattan', 'Onaga', 'St. George', 'Wamego', 'Westmoreland'],
  'Pratt': ['Pratt', 'Iuka', 'Byers', 'Cullison', 'Sawyer', 'Coats', 'Preston', 'Natrona', 'Byers', 'Coats', 'Cullison', 'Iuka', 'Natrona', 'Preston', 'Pratt', 'Sawyer'],
  'Rawlins': ['Atwood', 'McDonald', 'Ludell', 'Antonino', 'Calvert', 'Wheeler', 'Bird City', 'St. Francis', 'Antonino', 'Atwood', 'Bird City', 'Calvert', 'Ludell', 'McDonald', 'St. Francis', 'Wheeler'],
  'Reno': ['Hutchinson', 'South Hutchinson', 'Nickerson', 'Pretty Prairie', 'Abbyville', 'Arlington', 'Langdon', 'Plevna', 'Abbyville', 'Arlington', 'Hutchinson', 'Langdon', 'Nickerson', 'Plevna', 'Pretty Prairie', 'South Hutchinson'],
  'Republic': ['Belleville', 'Scandia', 'Cuba', 'Narka', 'Munden', 'Courtland', 'Kackley', 'Hollenberg', 'Belleville', 'Courtland', 'Cuba', 'Hollenberg', 'Kackley', 'Munden', 'Narka', 'Scandia'],
  'Rice': ['Lyons', 'Sterling', 'Little River', 'Chase', 'Alden', 'Raymond', 'Bushton', 'Silica', 'Alden', 'Bushton', 'Chase', 'Little River', 'Lyons', 'Raymond', 'Silica', 'Sterling'],
  'Riley': ['Manhattan', 'Junction City', 'Ogden', 'Grandview Plaza', 'Fort Riley', 'Leonardville', 'Randolph', 'Wheeler', 'Grandview Plaza', 'Junction City', 'Leonardville', 'Manhattan', 'Ogden', 'Randolph', 'Wheeler'],
  'Rooks': ['Stockton', 'Plainville', 'Codell', 'Damar', 'Woodston', 'Webster', 'Zurich', 'Palco', 'Codell', 'Damar', 'Palco', 'Plainville', 'Stockton', 'Webster', 'Woodston', 'Zurich'],
  'Rush': ['La Crosse', 'Bison', 'Timken', 'Alexander', 'Nekoma', 'Pawnee Rock', 'Garfield', 'Rozel', 'Alexander', 'Bison', 'Garfield', 'La Crosse', 'Nekoma', 'Pawnee Rock', 'Rozel', 'Timken'],
  'Russell': ['Russell', 'Gorham', 'Dorrance', 'Bunker Hill', 'Lucas', 'Luray', 'Ash Grove', 'Westfall', 'Ash Grove', 'Bunker Hill', 'Dorrance', 'Gorham', 'Lucas', 'Luray', 'Russell', 'Westfall'],
  'Saline': ['Salina', 'New Cambria', 'Gypsum', 'Assaria', 'Brookville', 'Falun', 'Kipp', 'Sharon Springs', 'Assaria', 'Brookville', 'Falun', 'Gypsum', 'Kipp', 'New Cambria', 'Salina', 'Sharon Springs'],
  'Scott': ['Scott City', 'Shallow Water', 'Leoti', 'Dighton', 'Healy', 'Alamota', 'Shields', 'Lane', 'Alamota', 'Dighton', 'Healy', 'Lane', 'Leoti', 'Scott City', 'Shallow Water', 'Shields'],
  'Sedgwick': ['Wichita', 'Derby', 'Haysville', 'Garden Plain', 'Colwich', 'Andale', 'Bentley', 'Walton', 'Andale', 'Bentley', 'Colwich', 'Derby', 'Garden Plain', 'Haysville', 'Walton', 'Wichita'],
  'Seward': ['Liberal', 'Kismet', 'Plains', 'Deerfield', 'Ryus', 'Point Rock', 'Hugoton', 'Moscow', 'Deerfield', 'Hugoton', 'Kismet', 'Liberal', 'Moscow', 'Plains', 'Point Rock', 'Ryus'],
  'Shawnee': ['Topeka', 'Auburn', 'Silver Lake', 'Rossville', 'Willard', 'Wakarusa', 'Berryton', 'Tecumseh', 'Auburn', 'Berryton', 'Rossville', 'Silver Lake', 'Tecumseh', 'Topeka', 'Wakarusa', 'Willard'],
  'Sheridan': ['Hoxie', 'Selden', 'Kanorado', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue', 'Nicodemus', 'Bogue', 'Grainfield', 'Grinnell', 'Hoxie', 'Kanorado', 'Nicodemus', 'Penokee', 'Selden'],
  'Sherman': ['Goodland', 'Kanorado', 'Edson', 'Ruleton', 'Brewster', 'Levant', 'Grainfield', 'Grinnell', 'Brewster', 'Edson', 'Goodland', 'Grainfield', 'Grinnell', 'Kanorado', 'Levant', 'Ruleton'],
  'Smith': ['Smith Center', 'Lebanon', 'Kensington', 'Athol', 'Gaylord', 'Long Island', 'Kirwin', 'Woodruff', 'Athol', 'Gaylord', 'Kensington', 'Kirwin', 'Lebanon', 'Long Island', 'Smith Center', 'Woodruff'],
  'Stafford': ['St. John', 'Hudson', 'Stafford', 'Macksville', 'Radium', 'Zenda', 'Nashville', 'St. Leo', 'Hudson', 'Macksville', 'Nashville', 'Radium', 'St. John', 'St. Leo', 'Stafford', 'Zenda'],
  'Stanton': ['Johnson City', 'Manter', 'Big Bow', 'Ulysses', 'Hugoton', 'Moscow', 'Plains', 'Deerfield', 'Big Bow', 'Deerfield', 'Hugoton', 'Johnson City', 'Manter', 'Moscow', 'Plains', 'Ulysses'],
  'Stevens': ['Hugoton', 'Moscow', 'Plains', 'Deerfield', 'Ryus', 'Point Rock', 'Ulysses', 'Satanta', 'Deerfield', 'Hugoton', 'Moscow', 'Plains', 'Point Rock', 'Ryus', 'Satanta', 'Ulysses'],
  'Sumner': ['Wellington', 'Caldwell', 'Oxford', 'Belle Plaine', 'Mulvane', 'Argonia', 'Geuda Springs', 'Mayfield', 'Argonia', 'Belle Plaine', 'Caldwell', 'Geuda Springs', 'Mayfield', 'Mulvane', 'Oxford', 'Wellington'],
  'Thomas': ['Colby', 'Brewster', 'Levant', 'Rexford', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue', 'Bogue', 'Brewster', 'Colby', 'Grainfield', 'Grinnell', 'Levant', 'Penokee', 'Rexford'],
  'Trego': ['Wakeeney', 'Ogallah', 'Collyer', 'Voda', 'WaKeeney', 'Ogallah', 'Collyer', 'Voda', 'Collyer', 'Ogallah', 'Voda', 'Wakeeney'],
  'Wabaunsee': ['Alma', 'Eskridge', 'Harveyville', 'Maple Hill', 'McFarland', 'Newbury', 'Wamego', 'St. George', 'Alma', 'Eskridge', 'Harveyville', 'Maple Hill', 'McFarland', 'Newbury', 'St. George', 'Wamego'],
  'Wallace': ['Sharon Springs', 'Wallace', 'Weskan', 'Kanorado', 'Grainfield', 'Grinnell', 'Penokee', 'Bogue', 'Bogue', 'Grainfield', 'Grinnell', 'Kanorado', 'Penokee', 'Sharon Springs', 'Wallace', 'Weskan'],
  'Washington': ['Washington', 'Hanover', 'Linn', 'Barnes', 'Greenleaf', 'Clifton', 'Hollenberg', 'Kackley', 'Barnes', 'Clifton', 'Greenleaf', 'Hanover', 'Hollenberg', 'Kackley', 'Linn', 'Washington'],
  'Wichita': ['Leoti', 'Dighton', 'Healy', 'Alamota', 'Shields', 'Lane', 'Scott City', 'Shallow Water', 'Alamota', 'Dighton', 'Healy', 'Lane', 'Leoti', 'Scott City', 'Shallow Water', 'Shields'],
  'Wilson': ['Fredonia', 'Neodesha', 'Buffalo', 'Coyville', 'New Albany', 'Benedict', 'Lorraine', 'Black Wolf', 'Benedict', 'Black Wolf', 'Buffalo', 'Coyville', 'Fredonia', 'Lorraine', 'Neodesha', 'New Albany'],
  'Woodson': ['Yates Center', 'Toronto', 'Piqua', 'Neosho Falls', 'Durand', 'Kalida', 'Liberty', 'Lakeside', 'Durand', 'Kalida', 'Lakeside', 'Liberty', 'Neosho Falls', 'Piqua', 'Toronto', 'Yates Center'],
  'Wyandotte': ['Kansas City', 'Edwardsville', 'Bonner Springs', 'Basehor', 'Tonganoxie', 'Lansing', 'Leavenworth', 'Easton', 'Basehor', 'Bonner Springs', 'Edwardsville', 'Easton', 'Kansas City', 'Lansing', 'Leavenworth', 'Tonganoxie'],
};

// List of all Kansas counties in alphabetical order
const List<String> kansasCounties = [
  'Allen', 'Anderson', 'Atchison', 'Barber', 'Barton', 'Bourbon', 'Brown', 'Butler',
  'Chase', 'Chautauqua', 'Cherokee', 'Cheyenne', 'Clark', 'Clay', 'Cloud', 'Coffey',
  'Comanche', 'Cowley', 'Crawford', 'Decatur', 'Dickinson', 'Doniphan', 'Douglas',
  'Edwards', 'Elk', 'Ellis', 'Ellsworth', 'Finney', 'Ford', 'Franklin', 'Geary',
  'Gove', 'Graham', 'Grant', 'Gray', 'Greeley', 'Greenwood', 'Hamilton', 'Harper',
  'Harvey', 'Haskell', 'Hodgeman', 'Jackson', 'Jefferson', 'Jewell', 'Johnson',
  'Kearny', 'Kingman', 'Kiowa', 'Labette', 'Lane', 'Leavenworth', 'Lincoln', 'Linn',
  'Logan', 'Lyon', 'Marion', 'Marshall', 'McPherson', 'Meade', 'Miami', 'Mitchell',
  'Montgomery', 'Morris', 'Morton', 'Nemaha', 'Neosho', 'Ness', 'Norton', 'Osage',
  'Osborne', 'Ottawa', 'Pawnee', 'Phillips', 'Pottawatomie', 'Pratt', 'Rawlins',
  'Reno', 'Republic', 'Rice', 'Riley', 'Rooks', 'Rush', 'Russell', 'Saline',
  'Scott', 'Sedgwick', 'Seward', 'Shawnee', 'Sheridan', 'Sherman', 'Smith',
  'Stafford', 'Stanton', 'Stevens', 'Sumner', 'Thomas', 'Trego', 'Wabaunsee',
  'Wallace', 'Washington', 'Wichita', 'Wilson', 'Woodson', 'Wyandotte'
]; 