name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.3'  # Set to your preferred Flutter version

      - name: Build Flutter web
        run: |
          cd colapp/frontend
          flutter pub get
          flutter build web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./colapp/frontend/build/web 